S2t retrieve and display ingredients
Mayden-Academy/2019-Aug-Bread-and-ifit-cobras pull request #1
Opened 2019-11-05 16:24 UTC by DanielGardiner

2019-11-05 16:41 UTC, jasonrees1 commented on package-lock.json
> +{
Mike: "why have you added all this shit, this means that they havent merged master when I told them to"

I think that he wants you to delete this file as its now in masters .gitignore

2019-11-05 16:43 UTC, jasonrees1 commented on src/Ingredients/DisplayIngredients.php
> +    public static function displayIngredients(array $ingredients): string {
should this { be on the next line?

2019-11-05 16:54 UTC, jasonrees1 commented on src/Ingredients/Ingredient.php
> +    public function getId(): int {
psr2

2019-11-06 09:24 UTC, jasonrees1 requested changes

2019-11-06 09:24 UTC, jasonrees1 commented on tests/Ingredients/DisplayIngredientsTest.php
> +$carrot = new class() extends Ingredient {
should this be class and if so should it have a capital letter?

2019-11-06 09:24 UTC, jasonrees1 commented on tests/Ingredients/DisplayIngredientsTest.php
> +require('../../src/Ingredients/Ingredient.php');
unit test should be run in the test folder

2019-11-06 09:24 UTC, jasonrees1 commented on tests/Ingredients/DisplayIngredientsTest.php
> +$carrot = new class() extends Ingredient {
see below also

2019-11-06 09:24 UTC, jasonrees1 commented on tests/Ingredients/DisplayIngredientsTest.php
> +require('../../src/Ingredients/Ingredient.php');
Though your test works fine otherwise

2019-11-06 11:07 UTC, avocadobelly commented on src/Ingredients/DisplayIngredients.php
> +     * @return array
please elaborate on array

2019-11-06 11:07 UTC, avocadobelly commented on src/Ingredients/DisplayIngredients.php
> +    /**
Add description for what the whole method does

2019-11-06 11:07 UTC, avocadobelly commented on tests/Ingredients/DisplayIngredientsTest.php
> +        var_dump($result);
is this the best way to display this information, using vardump?

2019-11-06 11:23 UTC, merged